# Use official Python image
FROM python:3.11-slim

# Set working directory inside container
WORKDIR /app

# Copy files to container
COPY . /app

# Install dependencies (if any)
RUN pip3 install flask

# Command to run app
CMD ["python", "app.py"]
